--------------------------------------------------------
--  File created - Thursday-July-02-2020   
--------------------------------------------------------
DROP TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI";
DROP TABLE "FARID_06972MOD1"."KASIR";
DROP TABLE "FARID_06972MOD1"."MENU";
DROP TABLE "FARID_06972MOD1"."TRANSAKSI";
--------------------------------------------------------
--  DDL for Table DETAIL_TRANSAKSI
--------------------------------------------------------

  CREATE TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI" 
   (	"KODE_MENU" VARCHAR2(4 BYTE), 
	"NO_NOTA" NUMBER(*,0), 
	"SUBTOTAL" NUMBER(9,0), 
	"QTY" NUMBER(3,0), 
	"TANGGAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  DDL for Table KASIR
--------------------------------------------------------

  CREATE TABLE "FARID_06972MOD1"."KASIR" 
   (	"ID_KASIR" NUMBER(*,0), 
	"NAMA" VARCHAR2(15 BYTE), 
	"ALAMAT" VARCHAR2(35 BYTE), 
	"NO_KTP" NUMBER(16,0), 
	"UMUR" NUMBER(2,0), 
	"TLP" NUMBER(13,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "FARID_06972MOD1"."MENU" 
   (	"KODE_MENU" VARCHAR2(4 BYTE), 
	"NAMA_MENU" VARCHAR2(20 BYTE), 
	"HARGA" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  DDL for Table TRANSAKSI
--------------------------------------------------------

  CREATE TABLE "FARID_06972MOD1"."TRANSAKSI" 
   (	"NO_NOTA" NUMBER(*,0), 
	"TOTAL" NUMBER(9,0), 
	"BAYAR" NUMBER(9,0), 
	"KEMBALI" NUMBER(9,0), 
	"ID_KASIR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
REM INSERTING into FARID_06972MOD1.DETAIL_TRANSAKSI
SET DEFINE OFF;
Insert into FARID_06972MOD1.DETAIL_TRANSAKSI (KODE_MENU,NO_NOTA,SUBTOTAL,QTY,TANGGAL) values ('m01','1','15000','1',to_date('01-07-2020','DD-MM-RRRR'));
REM INSERTING into FARID_06972MOD1.KASIR
SET DEFINE OFF;
Insert into FARID_06972MOD1.KASIR (ID_KASIR,NAMA,ALAMAT,NO_KTP,UMUR,TLP) values ('3','samsudin','Sidoarjo','1234','18','628339');
Insert into FARID_06972MOD1.KASIR (ID_KASIR,NAMA,ALAMAT,NO_KTP,UMUR,TLP) values ('1','farid','Surabaya','12312','19','62323');
Insert into FARID_06972MOD1.KASIR (ID_KASIR,NAMA,ALAMAT,NO_KTP,UMUR,TLP) values ('2','suep','surabaya','213','19','2313');
REM INSERTING into FARID_06972MOD1.MENU
SET DEFINE OFF;
Insert into FARID_06972MOD1.MENU (KODE_MENU,NAMA_MENU,HARGA) values ('m01','nasi goreng','15000');
REM INSERTING into FARID_06972MOD1.TRANSAKSI
SET DEFINE OFF;
Insert into FARID_06972MOD1.TRANSAKSI (NO_NOTA,TOTAL,BAYAR,KEMBALI,ID_KASIR) values ('5','18000','20000','2000','1');
Insert into FARID_06972MOD1.TRANSAKSI (NO_NOTA,TOTAL,BAYAR,KEMBALI,ID_KASIR) values ('3','28000','30000','5000','3');
Insert into FARID_06972MOD1.TRANSAKSI (NO_NOTA,TOTAL,BAYAR,KEMBALI,ID_KASIR) values ('4','24000','25000','1000','2');
Insert into FARID_06972MOD1.TRANSAKSI (NO_NOTA,TOTAL,BAYAR,KEMBALI,ID_KASIR) values ('1','25000','27000','5000','2');
Insert into FARID_06972MOD1.TRANSAKSI (NO_NOTA,TOTAL,BAYAR,KEMBALI,ID_KASIR) values ('2','22000','25000','3000','2');
--------------------------------------------------------
--  DDL for Index PK_KASIR
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARID_06972MOD1"."PK_KASIR" ON "FARID_06972MOD1"."KASIR" ("ID_KASIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  DDL for Index PK_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARID_06972MOD1"."PK_MENU" ON "FARID_06972MOD1"."MENU" ("KODE_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSAKSI
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARID_06972MOD1"."PK_TRANSAKSI" ON "FARID_06972MOD1"."TRANSAKSI" ("NO_NOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT" ;
--------------------------------------------------------
--  Constraints for Table DETAIL_TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI" MODIFY ("NO_NOTA" NOT NULL ENABLE);
  ALTER TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI" MODIFY ("KODE_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KASIR
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."KASIR" ADD CONSTRAINT "PK_KASIR" PRIMARY KEY ("ID_KASIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT"  ENABLE;
  ALTER TABLE "FARID_06972MOD1"."KASIR" MODIFY ("ID_KASIR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY ("KODE_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT"  ENABLE;
  ALTER TABLE "FARID_06972MOD1"."MENU" MODIFY ("KODE_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."TRANSAKSI" MODIFY ("ID_KASIR" NOT NULL ENABLE);
  ALTER TABLE "FARID_06972MOD1"."TRANSAKSI" ADD CONSTRAINT "PK_TRANSAKSI" PRIMARY KEY ("NO_NOTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMDEPOT"  ENABLE;
  ALTER TABLE "FARID_06972MOD1"."TRANSAKSI" MODIFY ("NO_NOTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DETAIL_TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI" ADD CONSTRAINT "FK_KODEMENU" FOREIGN KEY ("KODE_MENU")
	  REFERENCES "FARID_06972MOD1"."MENU" ("KODE_MENU") ENABLE;
  ALTER TABLE "FARID_06972MOD1"."DETAIL_TRANSAKSI" ADD CONSTRAINT "FK_NONOTA" FOREIGN KEY ("NO_NOTA")
	  REFERENCES "FARID_06972MOD1"."TRANSAKSI" ("NO_NOTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "FARID_06972MOD1"."TRANSAKSI" ADD CONSTRAINT "FK_ID_KASIR" FOREIGN KEY ("ID_KASIR")
	  REFERENCES "FARID_06972MOD1"."KASIR" ("ID_KASIR") ENABLE;
